"""
Virtual Machine for the Demon programming language.
This module executes bytecode generated by the bytecode compiler.
"""

from typing import List, Dict, Any, Optional, Union, Tuple
from enum import Enum
import time
from .bytecode import OpCode, Chunk

class RuntimeError(Exception):
    """Runtime error in the VM."""
    
    def __init__(self, message: str):
        self.message = message
        super().__init__(message)

class CallFrame:
    """Represents a call frame in the VM."""
    
    def __init__(self, function, ip: int, slots_start: int):
        self.function = function  # Function being executed
        self.ip = ip  # Instruction pointer
        self.slots_start = slots_start  # Start index in the stack for this frame

class Closure:
    """Represents a closure in the VM."""
    
    def __init__(self, function, upvalues=None):
        self.function = function
        self.upvalues = upvalues or []

class Upvalue:
    """Represents an upvalue in the VM."""
    
    def __init__(self, location: int):
        self.location = location  # Index in the stack
        self.closed = None  # Closed value

class NativeFunction:
    """Represents a native function in the VM."""
    
    def __init__(self, name: str, arity: int, function):
        self.name = name
        self.arity = arity
        self.function = function

class VM:
    """Virtual Machine for executing Demon bytecode."""
    
    def __init__(self, demon):
        self.demon = demon
        self.stack: List[Any] = []
        self.frames: List[CallFrame] = []
        self.globals: Dict[str, Any] = {}
        self.open_upvalues = None
        
        # Define native functions
        self.define_native("clock", 0, lambda: time.time())
    
    def define_native(self, name: str, arity: int, function):
        """Define a native function."""
        self.globals[name] = NativeFunction(name, arity, function)
    
    def interpret(self, chunk: Chunk) -> bool:
        """Interpret bytecode chunk."""
        try:
            # Create a dummy function for the top-level code
            main_function = {
                "chunk": chunk,
                "name": "main",
                "arity": 0
            }
            
            # Create a call frame for the main function
            self.frames.append(CallFrame(main_function, 0, 0))
            
            # Run the VM
            return self.run()
        except RuntimeError as error:
            print(f"Runtime error: {error.message}")
            return False
    
    def run(self) -> bool:
        """Run the VM."""
        while True:
            # Get current frame and instruction
            frame = self.frames[-1]
            instruction = frame.function["chunk"].code[frame.ip]
            frame.ip += 1
            
            # Dispatch based on instruction
            op = OpCode(instruction)
            
            if op == OpCode.CONSTANT:
                # Load constant onto stack
                constant_idx = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                constant = frame.function["chunk"].constants[constant_idx]
                self.stack.append(constant)
            
            elif op == OpCode.NIL:
                self.stack.append(None)
            
            elif op == OpCode.TRUE:
                self.stack.append(True)
            
            elif op == OpCode.FALSE:
                self.stack.append(False)
            
            elif op == OpCode.POP:
                self.stack.pop()
            
            elif op == OpCode.GET_LOCAL:
                # Get local variable
                slot = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                self.stack.append(self.stack[frame.slots_start + slot])
            
            elif op == OpCode.SET_LOCAL:
                # Set local variable
                slot = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                self.stack[frame.slots_start + slot] = self.stack[-1]
            
            elif op == OpCode.GET_GLOBAL:
                # Get global variable
                name_idx = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                name = frame.function["chunk"].constants[name_idx]
                
                if name not in self.globals:
                    raise RuntimeError(f"Undefined variable '{name}'.")
                
                self.stack.append(self.globals[name])
            
            elif op == OpCode.SET_GLOBAL:
                # Set global variable
                name_idx = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                name = frame.function["chunk"].constants[name_idx]
                
                if name not in self.globals:
                    raise RuntimeError(f"Undefined variable '{name}'.")
                
                self.globals[name] = self.stack[-1]
            
            elif op == OpCode.DEFINE_GLOBAL:
                # Define global variable
                name_idx = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                name = frame.function["chunk"].constants[name_idx]
                self.globals[name] = self.stack.pop()
            
            elif op == OpCode.EQUAL:
                b = self.stack.pop()
                a = self.stack.pop()
                self.stack.append(a == b)
            
            elif op == OpCode.GREATER:
                b = self.stack.pop()
                a = self.stack.pop()
                self.stack.append(a > b)
            
            elif op == OpCode.LESS:
                b = self.stack.pop()
                a = self.stack.pop()
                self.stack.append(a < b)
            
            elif op == OpCode.ADD:
                b = self.stack.pop()
                a = self.stack.pop()
                
                if isinstance(a, (int, float)) and isinstance(b, (int, float)):
                    self.stack.append(a + b)
                elif isinstance(a, str) and isinstance(b, str):
                    self.stack.append(a + b)
                else:
                    raise RuntimeError("Operands must be two numbers or two strings.")
            
            elif op == OpCode.SUBTRACT:
                b = self.stack.pop()
                a = self.stack.pop()
                
                if isinstance(a, (int, float)) and isinstance(b, (int, float)):
                    self.stack.append(a - b)
                else:
                    raise RuntimeError("Operands must be numbers.")
            
            elif op == OpCode.MULTIPLY:
                b = self.stack.pop()
                a = self.stack.pop()
                
                if isinstance(a, (int, float)) and isinstance(b, (int, float)):
                    self.stack.append(a * b)
                else:
                    raise RuntimeError("Operands must be numbers.")
            
            elif op == OpCode.DIVIDE:
                b = self.stack.pop()
                a = self.stack.pop()
                
                if isinstance(a, (int, float)) and isinstance(b, (int, float)):
                    if b == 0:
                        raise RuntimeError("Division by zero.")
                    self.stack.append(a / b)
                else:
                    raise RuntimeError("Operands must be numbers.")
            
            elif op == OpCode.MODULO:
                b = self.stack.pop()
                a = self.stack.pop()
                
                if isinstance(a, (int, float)) and isinstance(b, (int, float)):
                    if b == 0:
                        raise RuntimeError("Modulo by zero.")
                    self.stack.append(a % b)
                else:
                    raise RuntimeError("Operands must be numbers.")
            
            elif op == OpCode.NOT:
                self.stack.append(not self.is_truthy(self.stack.pop()))
            
            elif op == OpCode.NEGATE:
                if not isinstance(self.stack[-1], (int, float)):
                    raise RuntimeError("Operand must be a number.")
                self.stack.append(-self.stack.pop())
            
            elif op == OpCode.PRINT:
                count = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                
                values = []
                for _ in range(count):
                    values.insert(0, self.stringify(self.stack.pop()))
                
                print(" ".join(values))
            
            elif op == OpCode.JUMP:
                offset = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                frame.ip += offset
            
            elif op == OpCode.JUMP_IF_FALSE:
                offset = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                
                if not self.is_truthy(self.stack[-1]):
                    frame.ip += offset
            
            elif op == OpCode.LOOP:
                offset = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                frame.ip -= offset
            
            elif op == OpCode.CALL:
                arg_count = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                self.call_value(self.stack[-(arg_count + 1)], arg_count)
            
            elif op == OpCode.RETURN:
                result = self.stack.pop()
                
                # Close any upvalues for this frame
                self.close_upvalues(frame.slots_start)
                
                # Remove the frame
                self.frames.pop()
                
                # If this was the last frame, we're done
                if not self.frames:
                    return True
                
                # Remove the function and arguments from the stack
                while len(self.stack) > frame.slots_start:
                    self.stack.pop()
                
                # Push the result
                self.stack.append(result)
            
            elif op == OpCode.CLOSURE:
                function_idx = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                function = frame.function["chunk"].constants[function_idx]
                
                closure = Closure(function)
                self.stack.append(closure)
                
                # Capture upvalues
                for _ in range(len(function.get("upvalues", []))):
                    is_local = frame.function["chunk"].code[frame.ip] == 1
                    frame.ip += 1
                    index = frame.function["chunk"].code[frame.ip]
                    frame.ip += 1
                    
                    if is_local:
                        upvalue = self.capture_upvalue(frame.slots_start + index)
                    else:
                        upvalue = frame.function.get("upvalues", [])[index]
                    
                    closure.upvalues.append(upvalue)
            
            elif op == OpCode.GET_UPVALUE:
                slot = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                upvalue = frame.function.get("upvalues", [])[slot]
                
                if upvalue.closed is not None:
                    self.stack.append(upvalue.closed)
                else:
                    self.stack.append(self.stack[upvalue.location])
            
            elif op == OpCode.SET_UPVALUE:
                slot = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                upvalue = frame.function.get("upvalues", [])[slot]
                
                if upvalue.closed is not None:
                    upvalue.closed = self.stack[-1]
                else:
                    self.stack[upvalue.location] = self.stack[-1]
            
            elif op == OpCode.CLOSE_UPVALUE:
                self.close_upvalues(len(self.stack) - 1)
                self.stack.pop()
            
            elif op == OpCode.LIST:
                count = frame.function["chunk"].code[frame.ip]
                frame.ip += 1
                
                elements = []
                for _ in range(count):
                    elements.insert(0, self.stack.pop())
                
                self.stack.append(elements)
            
            elif op == OpCode.GET_INDEX:
                index = self.stack.pop()
                list_obj = self.stack.pop()
                
                if not isinstance(list_obj, list):
                    raise RuntimeError("Can only index into lists.")
                
                if not isinstance(index, int):
                    raise RuntimeError("List index must be an integer.")
                
                if index < 0 or index >= len(list_obj):
                    raise RuntimeError("List index out of bounds.")
                
                self.stack.append(list_obj[index])
            
            elif op == OpCode.SET_INDEX:
                value = self.stack.pop()
                index = self.stack.pop()
                list_obj = self.stack.pop()
                
                if not isinstance(list_obj, list):
                    raise RuntimeError("Can only index into lists.")
                
                if not isinstance(index, int):
                    raise RuntimeError("List index must be an integer.")
                
                if index < 0 or index >= len(list_obj):
                    raise RuntimeError("List index out of bounds.")
                
                list_obj[index] = value
                self.stack.append(value)
            
            else:
                raise RuntimeError(f"Unknown opcode: {op}")
    
    def call_value(self, callee, arg_count):
        """Call a value as a function."""
        if isinstance(callee, Closure):
            return self.call(callee, arg_count)
        elif isinstance(callee, NativeFunction):
            if arg_count != callee.arity:
                raise RuntimeError(f"Expected {callee.arity} arguments but got {arg_count}.")
            
            args = []
            for _ in range(arg_count):
                args.insert(0, self.stack.pop())
            
            result = callee.function(*args)
            self.stack.pop()  # Remove the function
            self.stack.append(result)
            return True
        else:
            raise RuntimeError("Can only call functions and classes.")
    
    def call(self, closure, arg_count):
        """Call a Demon function."""
        if arg_count != closure.function["arity"]:
            raise RuntimeError(f"Expected {closure.function['arity']} arguments but got {arg_count}.")
        
        # Create a new call frame
        frame = CallFrame(
            closure.function,
            0,  # Start at the beginning of the function
            len(self.stack) - arg_count - 1  # Stack slot where this frame starts
        )
        
        self.frames.append(frame)
        return True
    
    def capture_upvalue(self, location):
        """Capture an upvalue from the stack."""
        # Check if we already have an upvalue for this location
        prev_upvalue = None
        upvalue = self.open_upvalues
        
        while upvalue is not None and upvalue.location > location:
            prev_upvalue = upvalue
            upvalue = upvalue.next
        
        if upvalue is not None and upvalue.location == location:
            return upvalue
        
        # Create a new upvalue
        created_upvalue = Upvalue(location)
        created_upvalue.next = upvalue
        
        if prev_upvalue is None:
            self.open_upvalues = created_upvalue
        else:
            prev_upvalue.next = created_upvalue
        
        return created_upvalue
    
    def close_upvalues(self, last):
        """Close all upvalues at or above the given stack index."""
        while (self.open_upvalues is not None and
               self.open_upvalues.location >= last):
            upvalue = self.open_upvalues
            upvalue.closed = self.stack[upvalue.location]
            self.open_upvalues = upvalue.next
    
    def is_truthy(self, value):
        """Check if a value is truthy."""
        if value is None:
            return False
        if isinstance(value, bool):
            return value
        return True
    
    def stringify(self, value):
        """Convert a value to a string."""
        if value is None:
            return "nil"
        if isinstance(value, bool):
            return str(value).lower()
        if isinstance(value, (int, float)):
            text = str(value)
            if text.endswith(".0"):
                text = text[:-2]
            return text
        if isinstance(value, list):
            elements = [self.stringify(e) for e in value]
            return "[" + ", ".join(elements) + "]"
        return str(value)